### PR TITLE
styles(angel-preview): remove scroll bar

### PR DESCRIPTION
**Pull request by guilhermespopolin**
## What

Removes vertical scroll bar from _angel preview_

## Why

Its presence can be annoying sometimes while testing flows locally

## Before

before-scroll

## After

after-scroll

### CODE REVIEW

**Comment by gustaveen** [comment]
Hm, I assume te scrollbars only show up from the Angel preview. Since when you look at embark in the context of the onboarding the scrollbars don't show up. It would be nice to solve it the same way for both cases or WDYT :) 

We calculate the height for the `ChatContainer` if `hasHeader` is true. 
https://github.com/HedvigInsurance/embark/blob/master/src/Components/Passage.tsx#L33
Shouldn't we just pass `hasHeader={true}` for `<Passage>` and we would have the same behaviour :)

**Review by gustaveen — COMMENTED** [review]
Hm, I assume the scrollbars only show up in the Angel preview. Since when you look at embark in the context of the onboarding the scrollbars don't show up. It would be nice to solve it the same way for both cases or WDYT :) 

We calculate the height for the `ChatContainer` if `hasHeader` is true. 
https://github.com/HedvigInsurance/embark/blob/master/src/Components/Passage.tsx#L33
Shouldn't we just pass `hasHeader={true}` for `<Passage>` and we would have the same behaviour :)

**Comment by guilhermespopolin** [comment]
> Hm, I assume te scrollbars only show up in the Angel preview. Since when you look at embark in the context of the onboarding the scrollbars don't show up. It would be nice to solve it the same way for both cases or WDYT :)
> 
> We calculate the height for the `ChatContainer` if `hasHeader` is true. https://github.com/HedvigInsurance/embark/blob/master/src/Components/Passage.tsx#L33 Shouldn't we just pass `hasHeader={true}` for `<Passage>` and we would have the same behaviour :)

Awesome 🎉 
Soo much better. Thanks @gustaveen

**Comment by gustaveen** [comment]
Nemas problems! :relaxed: Awesome that you took the time to fix this @guilhermespopolin, it's been bothering me many times! 😆

**Review by gustaveen — APPROVED** [review]
:star:

**Pull request merged**
