### PR TITLE
added path to webonboarding for apps

### PR DESCRIPTION
**Pull request by MathiasOhrstrom**

### CODE REVIEW

**Review by palmenhq — APPROVED** [review]
Looks great, and welcome toe embark!

**Comment by palmenhq** [comment]
@MathiasOhrstrom if you don't want to wait for travis that's ok it's super slow and only does things on master anyways 😬

**Comment by MathiasOhrstrom** [comment]
@palmenhq Thanks 😊 
Why is does it run on a PR if it only does stuff on master?

**Comment by palmenhq** [comment]
@MathiasOhrstrom i don't know, good point. I will fix

**Pull request merged**
