### PR TITLE
Dockerize in prep for k8s-deploy

### PR DESCRIPTION
**Pull request by hedvigoscar**

### CODE REVIEW

**Comment by sampettersson** [comment]
Do we have an NPM token in travis? If so could we auto publish the package while we are at it? 😍

**Comment by hedvigoscar** [comment]
No, but we can easily add one 🙂

**Comment by hedvigoscar** [comment]
The big question is when to publish the package and what to name the version 😉

**Comment by sampettersson** [comment]
@hedvigoscar let's leave it for now then 😄

**Pull request merged**
