### PR TITLE
Update to Web Onboarding NO - English Combo

### PR DESCRIPTION
**Pull request by sampettersson**
Add `ExternalInsuranceProviderAction` to an NO flow, it checks agains the store for `Supports.DataCollectionNorway`, if its not supported it fallbacks to non insurely as previously.

### CODE REVIEW

**Review by hugokallstrom — APPROVED** [review]
When/how do we add `Supports.DataCollectionNorway` to the store?

**Comment by sampettersson** [comment]
@hugokallstrom I added to the iOS implementation so that it checks for this keyword and just returns `true` when it finds it 😄 I think that works kind of nicely. https://github.com/HedvigInsurance/ugglan/pull/421/files#diff-53dad1c3f396d45418ea55e5ab9b62a754422b90cd933b0c4c9fa39ebbc5f92dR90

**Comment by sampettersson** [comment]
This way we can launch updated stories and the clients will have to tell the story if it supports a specific feature, me and @robinandeer was thinking of using something similar for quoteCart like `Supports.QuoteCart`.

**Comment by hugokallstrom** [comment]
> This way we can launch updated stories and the clients will have to tell the story if it supports a specific feature, me and @robinandeer was thinking of using something similar for quoteCart like `Supports.QuoteCart`.

Cool! 👍

**Pull request merged**
