### PR TITLE
Fix story setting homeAndAccident instead of homeAccident

### PR DESCRIPTION
**Pull request by sampettersson**
In the offer step homeAccident is expected and not homeAndAccident

### CODE REVIEW

**Review by robinandeer — APPROVED** [review]
Oh that's bad! Nice that you found it

I guess needer flow is okay?

**Comment by sampettersson** [comment]
@robinandeer yep, needer flow was ok :)

**Comment by robinandeer** [comment]
@gustaveen Did you see this? Perhaps also a reason why we are getting errors in production...

**Comment by gustaveen** [comment]
Ah nice catch! 🙌 @sampettersson 
We don't use this in production @robinandeer :) We use `Web Onboarding SE - Switcher Without Accident` so this option isn't present.

**Pull request merged**
