### PR TITLE
Move HouseInformationAPI and PersonalInformationAPI into GraphQLAPI

### PR DESCRIPTION
**Pull request by sampettersson**
> Apps don't include support for either HouseInformationAPI or PersonalInformationAPI so migrating the last few remaning api calls in this story to the GraphQLAPI module.

### CODE REVIEW

**Review by robinandeer — APPROVED** [review]
That's cool! I assume you've tested this and we can verify in staging :)

**Comment by sampettersson** [comment]
@robinandeer I did test it a bit, I will verify in staging :)

**Comment by sampettersson** [comment]
Seems to work 🎉

**Comment by gustaveen** [comment]
Great! @sampettersson 🙌

**Comment by gustaveen** [comment]
Should we remove the resolvers later on then?

**Comment by robinandeer** [comment]
@gustaveen oh yes, let me add that to list of things to do on maintenance day!

**Pull request merged**
